version: '3.7'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    restart: always
    volumes:
      - directus-database:/directus/database
      - directus-uploads:/directus/uploads
      - directus-extensions:/directus/extensions
    env_file:
      - .env.directus
    environment:
      CORS_ENABLED: "true"
      STORAGE_LOCATIONS: "amazon"
      WEBSOCKETS_ENABLED: "false"
    networks:
      - vps-proxy

volumes:
  directus-database:
  directus-uploads:
  directus-extensions:

networks:
  vps-proxy:
    external: true