name: 'Build & Deploy Petit Roudoudou V2'

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Download dependencies'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: 'Setup .env'
        run: |
          cat <<EOF > .env
          ${{ vars.BUILD_ENV_FILE }}
          EOF
      - name: 'Build'
        run: 'yarn build'
        env:
          RECAPTCHA_SECRET: ${{ secrets.RECAPTCHA_SECRET }}

      - name: 'Save artifacts'
        uses: 'actions/upload-artifact@v2'
        with:
          name: 'dist'
          path: 'dist'

  deploy-to-cloud-run:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: 'Download artifacts'
        uses: 'actions/download-artifact@v2'
        with:
          name: 'dist'

      - name: 'Deploy to Cloud Run'
        run: 'gcloud run deploy --source dist/apps/storefront --project ${{ vars.GCP_PROJECT_ID }} --set-env-vars "NEXT_IMAGE_DOMAINS=${{ vars.NEXT_IMAGE_DOMAINS }}" --region ${{ vars.GCP_REGION_ID }} storefront'

  deploy-hosting:
    runs-on: ubuntu-latest
    needs: [deploy-to-cloud-run]
    steps:
      - uses: 'actions/checkout@v3'

      - name: Deploy Hosting (Firebase)
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
